[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/favicon.*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
